import type { FranchiseDossier } from "@/data/dossiers";

/* ══════════════════════════════════════════════════════════════
   DossierPanel — renders the merged best-supported dossier on a
   brand page. Source: src/data/dossiers/<slug>.json (generated by
   scripts/merge_dossiers.py). Self-contained: only renders the
   sections backed by data; everything else is suppressed.
   ══════════════════════════════════════════════════════════════ */

function fmt(v: unknown): string {
  if (v === null || v === undefined) return "—";
  if (typeof v === "string") return v;
  if (typeof v === "number") return v.toLocaleString();
  if (typeof v === "boolean") return v ? "yes" : "no";
  // Common structured-rate object: { rate, minimum, minimum_unit, calculation_basis }
  if (typeof v === "object") {
    const o = v as Record<string, unknown>;
    if ("rate" in o) {
      const rate = o.rate;
      const ratePct =
        typeof rate === "number"
          ? rate <= 1
            ? `${(rate * 100).toFixed(rate * 100 < 1 ? 2 : 1)}%`
            : `${rate}%`
          : String(rate);
      const min = o.minimum ?? o.minimum_amount;
      const minUnit = o.minimum_unit;
      const basis = o.calculation_basis ?? o.basis;
      const parts = [`${ratePct}${basis ? " of " + String(basis) : ""}`];
      if (min !== undefined && min !== null && min !== "") {
        parts.push(`min $${typeof min === "number" ? min.toLocaleString() : String(min)}${minUnit ? "/" + String(minUnit).replace(/^per\s+/, "") : ""}`);
      }
      return parts.join(" · ");
    }
    if ("low" in o && "high" in o) {
      const fmtMoney = (x: unknown) =>
        typeof x === "number" ? `$${x.toLocaleString()}` : String(x);
      return `${fmtMoney(o.low)} – ${fmtMoney(o.high)}`;
    }
    if ("value" in o) return fmt(o.value);
    if ("amount" in o) {
      const amt = o.amount;
      const note = o.note;
      const formatted = typeof amt === "number" ? `$${amt.toLocaleString()}` : String(amt);
      return note ? `${formatted} (${String(note).slice(0, 60)})` : formatted;
    }
    if ("current_rate" in o) {
      const rate = o.current_rate;
      const max = o.maximum_rate;
      const basis = o.basis;
      const r = typeof rate === "number" ? (rate <= 1 ? `${(rate * 100).toFixed(2)}%` : `${rate}%`) : String(rate);
      const m =
        max !== undefined && max !== null
          ? typeof max === "number"
            ? max <= 1
              ? `${(max * 100).toFixed(2)}%`
              : `${max}%`
            : String(max)
          : null;
      return `${r}${m ? " (cap " + m + ")" : ""}${basis ? " of " + String(basis) : ""}`;
    }
  }
  try {
    return JSON.stringify(v);
  } catch {
    return String(v);
  }
}

function asNumber(v: unknown): number | null {
  if (typeof v === "number") return v;
  if (typeof v === "string") {
    const n = Number(v.replace(/[^0-9.\-]/g, ""));
    return Number.isFinite(n) ? n : null;
  }
  return null;
}

function Card({
  title,
  children,
  tone = "default",
}: {
  title: string;
  children: React.ReactNode;
  tone?: "default" | "warning" | "success" | "danger";
}) {
  const toneCls =
    tone === "warning"
      ? "border-warning/30 bg-warning-light/40"
      : tone === "success"
        ? "border-success/30 bg-success-light/40"
        : tone === "danger"
          ? "border-danger/30 bg-danger-light/40"
          : "border-border bg-surface";
  return (
    <div className={`rounded-xl border ${toneCls} p-5 shadow-lg shadow-black/10`}>
      <div className="text-[9px] uppercase tracking-[0.15em] text-foreground/50 mb-2">{title}</div>
      <div className="text-sm leading-snug text-foreground/85">{children}</div>
    </div>
  );
}

function KV({ k, v }: { k: string; v: unknown }) {
  return (
    <div className="flex items-baseline justify-between gap-3 py-1 border-b border-border/40 last:border-b-0">
      <span className="text-[11px] uppercase tracking-wide text-foreground/55 shrink-0">{k}</span>
      <span className="text-sm text-foreground/90 text-right tabular-nums">{fmt(v)}</span>
    </div>
  );
}

export default function DossierPanel({ dossier }: { dossier: FranchiseDossier }) {
  const cs = dossier.current_snapshot;
  const econ = dossier.economics;
  const i19 = dossier.item19_quality;
  const i20 = dossier.item20_system_movement;
  const cb = dossier.contract_burden;
  const fs = dossier.financial_strength;
  const so = dossier.state_overrides;

  const techFees = econ.tech_fee_detail as
    | { tech_fees_itemized?: Array<{ name: string; annual_fee_usd: number; one_time_fee_usd?: number; optional?: boolean; purpose?: string }>; tech_fee_annual_total_required_only?: string; tech_fee_annual_total_with_optional?: string }
    | null
    | undefined;

  const auditOpinionStr = typeof fs.audit_opinion === "string" ? (fs.audit_opinion as string) : "";
  const opinionTone =
    auditOpinionStr.toLowerCase().includes("clean") || auditOpinionStr.toLowerCase().includes("unqualified")
      ? "success"
      : auditOpinionStr.toLowerCase().includes("going concern")
        ? "danger"
        : "default";

  const stateAddendaCount = (() => {
    if (!so || typeof so !== "object") return 0;
    const v = so as Record<string, unknown>;
    if (Array.isArray(v.states_with_addenda)) return v.states_with_addenda.length;
    return Object.keys(v).filter((k) => k !== "states_with_addenda").length;
  })();

  return (
    <section
      id="dossier"
      className="px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto py-10 border-t border-border/60"
      aria-labelledby="dossier-heading"
    >
      <div className="mb-6 flex items-baseline justify-between gap-3">
        <div>
          <div className="text-[10px] uppercase tracking-[0.15em] text-foreground/50 font-semibold">Merged FDD dossier</div>
          <h2 id="dossier-heading" className="text-2xl sm:text-3xl font-black tracking-tight">
            What the {cs.fdd_filing_year ?? ""} FDD actually says
          </h2>
        </div>
        <div className="text-[11px] text-foreground/55 text-right">
          Best-supported merged output<br />
          <span className="font-mono">{(dossier.source_evidence?.primary_run as string) ?? "—"}</span>
        </div>
      </div>

      {/* ── Headline current snapshot ── */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mb-6">
        <Card title="Franchise fee">
          <div className="text-lg font-bold tabular-nums">{fmt(cs.franchise_fee_headline)}</div>
        </Card>
        <Card title="Total investment">
          <div className="text-lg font-bold tabular-nums">{fmt(cs.investment_range_headline)}</div>
        </Card>
        <Card title="Royalty">
          <div className="text-sm font-semibold leading-snug">{fmt(cs.royalty_headline)}</div>
        </Card>
        <Card title="Ad / brand fund">
          <div className="text-sm font-semibold leading-snug">{fmt(cs.ad_fund_headline)}</div>
        </Card>
      </div>

      {/* ── Tech fee stack (if surfaced) ── */}
      {techFees && Array.isArray(techFees.tech_fees_itemized) && techFees.tech_fees_itemized.length > 0 && (
        <div className="mb-6">
          <div className="text-[10px] uppercase tracking-[0.15em] text-foreground/50 font-semibold mb-3">Tech-fee stack (annual)</div>
          <div className="rounded-xl border border-border bg-surface shadow-lg shadow-black/10 p-5">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-x-6 gap-y-1 text-[12px]">
              {techFees.tech_fees_itemized.slice(0, 24).map((f, i) => (
                <div key={i} className="flex items-baseline justify-between gap-3 py-1 border-b border-border/30 last:border-b-0">
                  <span className="text-foreground/80 truncate">{f.name}{f.optional ? " (optional)" : ""}</span>
                  <span className="tabular-nums text-foreground/70 shrink-0">
                    {asNumber(f.annual_fee_usd) !== null ? `$${(asNumber(f.annual_fee_usd) ?? 0).toLocaleString()}/yr` : "—"}
                  </span>
                </div>
              ))}
            </div>
            {(techFees.tech_fee_annual_total_required_only || techFees.tech_fee_annual_total_with_optional) && (
              <div className="mt-3 pt-3 border-t border-border/40 text-[12px] text-foreground/75 flex flex-wrap gap-x-6 gap-y-1">
                {techFees.tech_fee_annual_total_required_only && (
                  <span><strong>Required total:</strong> {techFees.tech_fee_annual_total_required_only}</span>
                )}
                {techFees.tech_fee_annual_total_with_optional && (
                  <span><strong>With optional:</strong> {techFees.tech_fee_annual_total_with_optional}</span>
                )}
              </div>
            )}
          </div>
        </div>
      )}

      {/* ── 2-up: Item 19 quality + Item 20 system movement ── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3 mb-6">
        <Card title="Item 19 quality">
          {cs.item_19_present ? (
            <div className="space-y-1">
              <KV k="Cohort n" v={i19.cohort_n} />
              <KV k="Average AUV" v={i19.average ?? (i19 as Record<string, unknown>).average_auv} />
              <KV k="Median AUV" v={i19.median ?? (i19 as Record<string, unknown>).median_auv} />
              <KV k="High / low" v={i19.high_low} />
              <KV k="Presentation basis" v={i19.presentation_basis} />
            </div>
          ) : (
            <div className="text-foreground/60">Item 19 not surfaced in the merged dossier.</div>
          )}
        </Card>
        <Card title="Item 20 system movement">
          <div className="space-y-1">
            <KV k="System total" v={i20.system_total} />
            <KV k="Franchised" v={i20.franchised} />
            <KV k="Company-owned" v={i20.company_owned} />
            <KV k="Openings (yr)" v={i20.openings} />
            <KV k="Terminations (yr)" v={i20.terminations} />
            <KV k="Non-renewals (yr)" v={i20.non_renewals} />
            <KV k="Transfers (yr)" v={i20.transfers} />
          </div>
        </Card>
      </div>

      {/* ── Contract burden + financial strength + state overrides ── */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-3 mb-6">
        <Card title="Contract burden">
          <div className="space-y-1">
            <KV k="Termination (cause)" v={cb.termination_with_cause} />
            <KV k="Franchisee termination" v={cb.termination_by_franchisee} />
            <KV k="Transfer" v={cb.transfer} />
            <KV k="Non-compete (in-term)" v={cb.noncompete_in_term} />
            <KV k="Non-compete (post-term)" v={cb.noncompete_post_term} />
          </div>
        </Card>
        <Card title="Financial strength" tone={opinionTone}>
          <div className="space-y-1">
            <KV k="Auditor" v={fs.auditor} />
            <KV k="Opinion" v={fs.audit_opinion} />
            <KV k="Opinion date" v={fs.audit_opinion_date} />
            <KV k="FYE" v={fs.fiscal_year_end} />
            <KV k="Total revenue" v={fs.total_revenue} />
            <KV k="Net income" v={fs.net_income} />
            <KV k="Bankruptcy flag" v={fs.bankruptcy_flag} />
          </div>
        </Card>
        <Card title="State overrides">
          {stateAddendaCount > 0 ? (
            <div className="text-sm">
              <div className="font-semibold mb-1">{stateAddendaCount} state{stateAddendaCount === 1 ? "" : "s"} with overrides</div>
              {so && typeof so === "object" && Array.isArray((so as Record<string, unknown>).states_with_addenda) && (
                <div className="text-[12px] text-foreground/70 leading-snug">
                  {(((so as Record<string, unknown>).states_with_addenda as string[]) ?? []).join(", ")}
                </div>
              )}
            </div>
          ) : (
            <div className="text-foreground/60">No state-level overrides surfaced.</div>
          )}
        </Card>
      </div>

      {/* ── Validation questions for diligence calls ── */}
      {dossier.validation_questions.length > 0 && (
        <div className="mb-6">
          <div className="text-[10px] uppercase tracking-[0.15em] text-foreground/50 font-semibold mb-3">Validation questions for the franchisor</div>
          <div className="rounded-xl border border-border bg-surface shadow-lg shadow-black/10 p-5">
            <ul className="space-y-2 text-sm leading-snug">
              {dossier.validation_questions.slice(0, 8).map((q, i) => (
                <li key={i} className="flex items-baseline gap-2">
                  <span className="text-foreground/40">{i + 1}.</span>
                  <span className="text-foreground/85">{q}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* ── Filing changes vs harvested prior runs ── */}
      {dossier.filing_changes.length > 0 && (
        <div className="mb-6">
          <div className="text-[10px] uppercase tracking-[0.15em] text-foreground/50 font-semibold mb-3">Filing-year changes vs prior runs</div>
          <div className="rounded-xl border border-border bg-surface shadow-lg shadow-black/10 p-5">
            <div className="space-y-2 text-[12px]">
              {dossier.filing_changes.slice(0, 8).map((fc, i) => (
                <div key={i} className="flex flex-wrap items-baseline gap-x-3 gap-y-1 border-b border-border/30 pb-2 last:border-b-0">
                  <span className="font-mono text-foreground/65">{fc.field}</span>
                  <span className="text-foreground/55">was <span className="text-foreground/80">{fmt(fc.old_value)}</span></span>
                  <span className="text-foreground/55">→ now <span className="text-foreground/90 font-semibold">{fmt(fc.current_value)}</span></span>
                  <span className="text-[10px] text-foreground/45 font-mono">({fc.from_run})</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ── Red flags surfaced ── */}
      {dossier.red_flags.length > 0 && (
        <div className="mb-6">
          <div className="text-[10px] uppercase tracking-[0.15em] text-foreground/50 font-semibold mb-3">Red flags from the merged dossier</div>
          <div className="space-y-2">
            {dossier.red_flags.slice(0, 6).map((rf, i) => {
              const sev =
                rf.severity === "warning"
                  ? "border-warning/30 bg-warning-light/40 text-warning"
                  : rf.severity === "critical"
                    ? "border-danger/30 bg-danger-light/40 text-danger"
                    : "border-cyan/30 bg-cyan-light/40 text-cyan";
              return (
                <div key={i} className={`rounded-lg border ${sev} p-3 text-sm flex items-start gap-3`}>
                  <span className="text-[10px] uppercase tracking-wider font-bold shrink-0 mt-0.5">{rf.severity}</span>
                  <div className="text-foreground/85">
                    <span className="text-[10px] uppercase tracking-wider text-foreground/50 mr-2">{rf.kind}</span>
                    {rf.summary}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      <div className="text-[10px] text-foreground/45 mt-2">
        Source: merged dossier from {(dossier.source_evidence?.primary_run as string) ?? "primary run"}
        {Array.isArray(dossier.source_evidence?.harvest_runs) && (dossier.source_evidence?.harvest_runs as string[]).length > 0 && (
          <> + {(dossier.source_evidence?.harvest_runs as string[]).length} harvest run{(dossier.source_evidence?.harvest_runs as string[]).length === 1 ? "" : "s"}</>
        )}
        . Internal unresolveds suppressed: {dossier.internal_unresolveds.length}.
      </div>
    </section>
  );
}
