/* ══════════════════════════════════════════════════════
   Franchise dossiers — merged best-supported output per franchise.
   Generated by scripts/merge_dossiers.py from runs/ + site data.
   Source of truth for: fee stack, Item 19 quality, Item 20 system
   movement, contract burden, state overrides, financial strength,
   internal unresolveds.
   ══════════════════════════════════════════════════════ */

import mcdonalds from "./mcdonalds.json";
import ivybrook from "./ivybrook-academy.json";
import burgerKing from "./burger-king.json";
import qdoba from "./qdoba-mexican-eats.json";
import rocky from "./rocky-rococo-pizza-and-pasta.json";
import chickFilA from "./chick-fil-a.json";
import anago from "./anago-cleaning-systems.json";
import cruise from "./cruise-planners.json";
import cupbop from "./cupbop.json";
import jiffy from "./jiffy-lube.json";
import joint from "./the-joint-chiropractic.json";

/* ── Schema ── */
export type FranchiseDossier = {
  slug: string;
  name: string;
  schema_version: number;
  current_snapshot: {
    legal_name?: string | null;
    parent?: string | null;
    headquarters?: string | null;
    fdd_filing_year?: number | null;
    issuance_date?: string | null;
    franchise_fee_headline?: string | null;
    investment_range_headline?: string | null;
    royalty_headline?: unknown;
    ad_fund_headline?: unknown;
    term_headline?: unknown;
    renewal_headline?: unknown;
    territory_headline?: unknown;
    item_19_present?: boolean;
    system_total_units?: number | string | null;
    franchised_units?: number | string | null;
    company_owned_units?: number | string | null;
  };
  economics: {
    initial_fees_by_format?: Record<string, unknown> | null;
    investment_by_format?: Record<string, unknown> | null;
    recurring_fees_raw?: Record<string, unknown> | null;
    tech_fee_detail?: Record<string, unknown> | null;
  };
  item19_quality: Record<string, unknown>;
  item20_system_movement: Record<string, unknown>;
  contract_burden: Record<string, unknown>;
  territory_reality: Record<string, unknown>;
  state_overrides: Record<string, unknown> | null;
  financial_strength: Record<string, unknown>;
  red_flags: Array<{ severity: string; kind: string; summary: string }>;
  validation_questions: string[];
  filing_changes: Array<{ field: string; from_run: string; old_value: unknown; current_value: unknown }>;
  source_evidence: Record<string, unknown>;
  internal_unresolveds: Array<{ topic: string; reason: string }>;
};

const REGISTRY: Record<string, FranchiseDossier> = {
  mcdonalds: mcdonalds as unknown as FranchiseDossier,
  "ivybrook-academy": ivybrook as unknown as FranchiseDossier,
  "burger-king": burgerKing as unknown as FranchiseDossier,
  "qdoba-mexican-eats": qdoba as unknown as FranchiseDossier,
  "rocky-rococo-pizza-and-pasta": rocky as unknown as FranchiseDossier,
  "chick-fil-a": chickFilA as unknown as FranchiseDossier,
  "anago-cleaning-systems": anago as unknown as FranchiseDossier,
  "cruise-planners": cruise as unknown as FranchiseDossier,
  cupbop: cupbop as unknown as FranchiseDossier,
  "jiffy-lube": jiffy as unknown as FranchiseDossier,
  "the-joint-chiropractic": joint as unknown as FranchiseDossier,
};

export function getDossier(slug: string): FranchiseDossier | null {
  return REGISTRY[slug] ?? null;
}

export function hasDossier(slug: string): boolean {
  return slug in REGISTRY;
}

export const DOSSIER_SLUGS = Object.keys(REGISTRY);
